spring:
  security:
    user:
      name: marsel
      password: marsel
  application:
    name: manas-fen
  datasource:
    url: jdbc:postgresql://localhost:5432/manas
    driver-class-name: org.postgresql.Driver
    username: marselMadanbekov
    password: madanbekovmarsel
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    path: /error


custom:
  parameters:
    surveys:
      page-size: 10
    teachers:
      page-size: 10
      photo:
        width: 690
        height: 520
    articles:
      page-size: 10
      photo:
        width: 690
        height: 520
    links:
      page-size: 10
      photo:
        width: 1920
        height: 1080
    news:
      page-size: 10
      photo:
        width: 1920
        height: 1080
    upload-photo-directory: /development/manas-fen/images/
